### ISSUE TITLE
deeplearning4j for Mini PC's / Linux ARMv7-hf

### ISSUE THREAD

**Issue by HKMaster** [deeplearning4j/libnd4j#782] opened 2018-02-19 15:35 UTC
Hello, I'm using Odroid-XU4 that has an ARMv7-hf CPU inside, to run a java application that uses DL4J in order to use a Convolutional Neural Network pre-trained model to recognize characters. When i first run the application on my Odroid, it crashed throwing an "Unsatisfied Link Error" since it couldn't find its ARM-based native libraries. 

I could't understand why they always publish builds for almost all platforms, but they don't do that for ARM. I tried to build my own version directly on my Odroid by following [This instruction set](https://github.com/deeplearning4j/libnd4j/blob/master/RaspberryPi2.md), although it is directed for RaspberryPI users but i used it since my Odroid has the same CPU found in the RaspberryPI 3, however it didn't work. After running the third Instruction "**$./buildnativeoperations.sh -o linux-armhf**" an error occured saying that it couldn't find the toolchain file "Home/UserDir/raspberrypi/pi.cmake".

**So, how to solve this problem and is there any DL4J pre-built binaries for Linux ARMv7-hf out there?!**

thanks in advance

**Comment by saudet** [comment] 2018-02-20 02:59
Duplicate of https://github.com/deeplearning4j/nd4j/issues/2363

**Closed by saudet** 2018-02-20 02:59 UTC
Labels: duplicate, enhancement
