### ISSUE TITLE
SIGSEGV in shape::TAD::init

### ISSUE THREAD

**Issue by EdwinLUSTlab** [deeplearning4j/libnd4j#191] opened 2016-05-19 10:01 UTC
I am running the GravesLSTMCharModellingExample and got a program crash after around 800 iterations when using the nd4j-native 0.4-rc3.9 backend on OSX 10.11.4

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000001250af6e9, pid=5417, tid=5891
#
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libnd4j.dylib+0x236e9]  shape::TAD::init(int*, int*, int)+0x249
```

Hardware:
iMac (27-inch, Late 2013), 3.5 GHz Intel Core i7, 16 GB 1600 MHz DDR3

Additional error information:
https://gist.github.com/EdwinLUSTlab/84b21062cf3ee30bc683daae8c302a3a

**Comment by agibsonccc** [comment] 2016-05-22 04:32
@eraly @nyghtowl @saudet Have any of you been able to reproduce this?

**Comment by saudet** [comment] 2016-05-22 11:56
Can't reproduce it on Linux. Will try on Mac, but that'll take a while...

**Comment by saudet** [comment] 2016-05-22 14:14
BTW, seems to be the same issue as https://github.com/deeplearning4j/libnd4j/issues/191

**Comment by saudet** [comment] 2016-05-22 14:34
That didn't long. Yes me too I can reproduce it on Mac. So it's something with the runtime...

**Comment by agibsonccc** [comment] 2016-05-22 14:37
Debug or release mode I wonder..?

**Comment by saudet** [comment] 2016-05-22 23:44
Nope, it's not a runtime issue. It get this when executed in Valgrind:
```
Number of parameters in layer 0: 223000
Number of parameters in layer 1: 321400
Number of parameters in layer 2: 15477
Total number of network parameters: 559877
==3623== Mismatched free() / delete / delete []
==3623==    at 0x4C2A1A0: operator delete(void*) (vg_replace_malloc.c:576)
==3623==    by 0x30D0DEC4: shape::shapeBuffer(int, int*) (shape.h:2682)
==3623==    by 0x30D297E2: functions::transform::ops::SoftMax<float>::execSpecial(float*, int*, float*, int*, float*) (transform.h:3943)
==3623==    by 0x30D21849: functions::transform::Transform<float>::exec(float*, int*, float*, int*, float*) (transform.h:285)
==3623==    by 0x30D10895: NativeOpExcutioner<float>::execTransform(int, float*, int*, float*, int*, float*) (NativeOpExcutioner.h:542)
==3623==    by 0x30D00EA8: NativeOps::execTransformFloat(long long*, int, long long, long long, long long, long long, long long) (NativeOps.cpp:1332)
==3623==    by 0x30F8622E: JIJ::Java_org_nd4j_nativeblas_NativeOps_execTransformFloat_(__complex __complex __complex __complex) (in /tmp/javacpp1083004137001/libjnind4j.so)
==3623==    by 0x8083833: ???
==3623==    by 0x8074FFC: ???
==3623==    by 0x8074FFC: ???
==3623==    by 0x8074D7F: ???
==3623==    by 0x8074E53: ???
==3623==  Address 0x2d738c80 is 0 bytes inside a block of size 8 alloc'd
==3623==    at 0x4C298BB: operator new[](unsigned long) (vg_replace_malloc.c:423)
==3623==    by 0x30D0D6FF: shape::calcStrides(int*, int, int) (shape.h:2439)
==3623==    by 0x30D0D7D5: shape::calcStrides(int*, int) (shape.h:2482)
==3623==    by 0x30D0DE04: shape::shapeBuffer(int, int*) (shape.h:2668)
==3623==    by 0x30D297E2: functions::transform::ops::SoftMax<float>::execSpecial(float*, int*, float*, int*, float*) (transform.h:3943)
==3623==    by 0x30D21849: functions::transform::Transform<float>::exec(float*, int*, float*, int*, float*) (transform.h:285)
==3623==    by 0x30D10895: NativeOpExcutioner<float>::execTransform(int, float*, int*, float*, int*, float*) (NativeOpExcutioner.h:542)
==3623==    by 0x30D00EA8: NativeOps::execTransformFloat(long long*, int, long long, long long, long long, long long, long long) (NativeOps.cpp:1332)
==3623==    by 0x30F8622E: JIJ::Java_org_nd4j_nativeblas_NativeOps_execTransformFloat_(__complex __complex __complex __complex) (in /tmp/javacpp1083004137001/libjnind4j.so)
==3623==    by 0x8083833: ???
==3623==    by 0x8074FFC: ???
==3623==    by 0x8074FFC: ???
==3623== 
```

**Comment by agibsonccc** [comment] 2016-05-23 03:24
https://github.com/deeplearning4j/libnd4j/pull/207 Did this fix it?

**Comment by saudet** [comment] 2016-05-23 06:49
Seems like it. Valgrind stopped complaining and it doesn't crash anymore on Mac either.

**Comment by agibsonccc** [comment] 2016-05-23 09:08
Closing this.

**Closed by agibsonccc** 2016-05-23 09:08 UTC
