### ISSUE TITLE
OS X Build failure

### ISSUE THREAD

**Issue by wellner** [deeplearning4j/libnd4j#226] opened 2016-06-02 17:41 UTC
I just cloned the repo and have followed the instructions to the letter for building on a Mac.  I'm getting the following errors:

[ERROR_LOG.TXT](https://github.com/deeplearning4j/libnd4j/files/296164/ERROR_LOG.TXT)

Clang version:
mm212717-PC:libnd4j wellner$ clang-omp --version
clang version 3.5.0 
Target: x86_64-apple-darwin15.5.0
Thread model: posix

cmake --version
cmake version 3.4.3

mm212717-PC:libnd4j wellner$ export
declare -x Apple_PubSub_Socket_Render="/private/tmp/com.apple.launchd.GbvkBkYaTj/Render"
declare -x DISPLAY="/private/tmp/com.apple.launchd.MXHjnToXZT/org.macosforge.xquartz:0"
declare -x HOME="/Users/wellner"
declare -x JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home"
declare -x LANG="en_US.UTF-8"
declare -x LIBND4J_HOME="/Users/wellner/Devel/mandolin-dl/libnd4j"
declare -x LOGNAME="wellner"
declare -x OLDPWD="/Users/wellner/Devel/mandolin-dl/javacpp"
declare -x PATH="/usr/local/Cellar/clang-omp/2015-04-01/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin"
declare -x PWD="/Users/wellner/Devel/mandolin-dl/libnd4j"
declare -x SHELL="/bin/bash"
declare -x SHLVL="1"
declare -x SSH_AUTH_SOCK="/private/tmp/com.apple.launchd.y2XbOBJ3CA/Listeners"
declare -x TERM="xterm-256color"
declare -x TERM_PROGRAM="Apple_Terminal"
declare -x TERM_PROGRAM_VERSION="361.1"
declare -x TERM_SESSION_ID="65F7BB0B-058E-4915-B597-409FB79C3190"
declare -x TMPDIR="/var/folders/q1/r4xjpn6n3lvd5g61syhb7kzmw70lp6/T/"
declare -x USER="wellner"
declare -x XPC_FLAGS="0x0"
declare -x XPC_SERVICE_NAME="0"
declare -x __CF_USER_TEXT_ENCODING="0x38704EC6:0x0:0x0"

**Comment by raver119** [comment] 2016-06-02 17:50
Pull master once again please, and try again.

**Comment by wellner** [comment] 2016-06-02 17:57
So fast!  Progress, but another issue:

[ERROR_LOG_2.TXT](https://github.com/deeplearning4j/libnd4j/files/296197/ERROR_LOG_2.TXT)

**Comment by raver119** [comment] 2016-06-02 18:02
Any chance you could try later versions of CLang?

**Comment by wellner** [comment] 2016-06-02 18:10
Yup - will try that.

**Comment by raver119** [comment] 2016-06-02 18:19
Cool. Please do that, and provide me with output log from fresh CLang please

**Comment by wellner** [comment] 2016-06-02 19:01
Do you have a quick pointer on how best to do this with clang-omp?  Looks like newer versions of Clang directly support OMP.  But the build now can't detect OMP (snippet below) if I simply point to clang-3.8 (instead of clang-omp)

......
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS) 
-- Could NOT find MKL (missing:  MKL_LIBRARY_DIR LIB_MKL_RT LIB_PTHREAD MKL_INCLUDE_DIR) 

Any help appreciated (bumping against my lack of c-compiler know-how here)

**Comment by wellner** [comment] 2016-06-02 19:21
Ignore previous message .. standby, I had an incorrect version of the compiler I believe (without omp)

**Comment by wellner** [comment] 2016-06-02 20:05
Ok - I found an older version of libnd4j that I did compile earlier.  I went back and followed the instructions there (using clang 3.5 with clang-omp) - it compiles fine.  It also compiles fine with clang-3.8.   The master HEAD fails, however, with both 3.5 and 3.8. With 3.5 the errors are those in ERROR_LOG_2.TXT (above). With 3.8, I get: 
[LOG_HEAD_VERSION_Clang-3.8.TXT](https://github.com/deeplearning4j/libnd4j/files/296408/LOG_HEAD_VERSION_Clang-3.8.TXT)

For the OLD version using Clang 3.8 (and 3.5) I get this output:
[LOG_OLD_VERSION_Clang-3.8.TXT](https://github.com/deeplearning4j/libnd4j/files/296410/LOG_OLD_VERSION_Clang-3.8.TXT)

**Comment by raver119** [comment] 2016-06-02 20:17
To be clear: Clang 3.8 compiles previous versions fine. And cant compile current master, complaining for absent omp.h. Right?

**Comment by wellner** [comment] 2016-06-02 20:19
Yup - that's right.

**Comment by raver119** [comment] 2016-06-02 22:14
So, in short: CLang has no full support for OpenMP 4.0, and your issue is caused by our latest changes. Starting next release we fully use SIMD instructions, everywhere its possible, and CLang just can't use that yet.

So quick fix will be applied now, but for you next release won't be as great as for linux users :)

**Comment by raver119** [comment] 2016-06-02 22:14
Also, please get back to your initial version of clang-omp

**Comment by wellner** [comment] 2016-06-02 22:22
Ah - ok; good to know.  Linux is actually target platform but nice to test things out on OS X. The older version that currently works and a quick fix on latest will be sufficient for me :)

**Comment by eraly** [comment] 2016-06-02 22:49
Fixes for
https://github.com/deeplearning4j/libnd4j/pull/227

**Comment by raver119** [comment] 2016-06-02 22:58
I'm closing this issue now. If something goes wrong on your system - please, feel free to reopen it. However, we've tested, and it helped.

**Closed by raver119** 2016-06-02 22:58 UTC
Labels: bug

**Comment by wellner** [comment] 2016-06-03 15:14
Confirming the build works fine now.  Thanks!
