### ISSUE TITLE
Different training results with CUDA Backend

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#192] opened 2016-05-19 17:44 UTC
The project in https://github.com/treo/dl4j-different-behavior results in very different learning behavior. 

With `nd4j-native` it starts out with a lower score (~7) and quickly reduced it (~6), resulting in an evaluation F1 score of 0.12.

With `nd4j-cuda-7.5` on the other hand, it starts with an already quite high score (~49) and while it can reduce it within an iteration to a lower one (~37), this is a lot higher than the CPU score and the evaluation F1 score is just 0.0259.

**Comment by AlexDBlack** [comment] 2016-05-20 06:20
Probably caused by this: https://github.com/deeplearning4j/nd4j/issues/953

**Comment by AlexDBlack** [comment] 2016-05-20 13:15
@treo should be fixed I think with the above-mentioned issue. Scores look good to me; slight differences but I think this is just numerical precision.

Native:
o.d.o.l.ScoreIterationListener - Score at iteration 0 is 7.568350026649906
o.d.o.l.ScoreIterationListener - Score at iteration 1 is 7.3585399953222215
o.d.o.l.ScoreIterationListener - Score at iteration 2 is 7.187918821158891
o.d.o.l.ScoreIterationListener - Score at iteration 3 is 6.993106729017625

CUDA:
o.d.o.l.ScoreIterationListener - Score at iteration 0 is 7.570596482333971
o.d.o.l.ScoreIterationListener - Score at iteration 1 is 7.360786788854441
o.d.o.l.ScoreIterationListener - Score at iteration 2 is 7.190150670789927
o.d.o.l.ScoreIterationListener - Score at iteration 3 is 6.995355859146421

**Closed by AlexDBlack** 2016-05-20 13:15 UTC

**Comment by treo** [comment] 2016-05-20 14:08
Right, works correctly now.
